language: node_js
node_js:
  - 0.10
  - 0.9
  - 0.8

secure: "kgO1SMpQrnhb0dls9isFhnliY6/U7AsLoENUeHse4/1/gbOKVBhg31ZV9NH60TmJnmu+ZPVdcZTqA/hEPiHSytBnCoiBsJdMDAVYunt1F4/h3SvcvO8fbwgvabq27BURY6i7f6QzWwkLc6sedn2WQBFmFJShnsMmgoEAm2goqsk="
